### ISSUE TITLE
Feedback al usuario cuando hay un error

### ISSUE THREAD

**Issue by urkonn** [vaquer/HerramientaFormatosGob#2]
Cuando un usuario sube un archivo no válido o corrupto debería ver qué ocurre

```
Internal Server Error: /converter/convert/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/project/FormatTools/converter/views.py", line 27, in convert_to
    converter_engine = XLSConverter.get_converter(format_to, xls_file)
  File "/project/FormatTools/converter/converters.py", line 31, in get_converter
    return decoder(memory_file=memory_file)
  File "/project/FormatTools/converter/converters.py", line 142, in __init__
    super(XLSToJSONConverter, self).__init__(*args, **kwargs)
  File "/project/FormatTools/converter/converters.py", line 54, in __init__
    self.xls_file = xlrd.open_workbook(file_contents=self.memory_file.read(), encoding_override="cp1252")
  File "/usr/local/lib/python2.7/site-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/site-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/site-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/site-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '<?xml ve'
[06/Jul/2016 18:45:23] "POST /converter/convert/ HTTP/1.1" 500 14347
```

**Comment by vaquer** [comment]
@urkonn  Que ha pasado con esto? lo cerramos?
